### PR TITLE
Allow supervisorctl override

### PR DESCRIPTION
**Pull request by gsmethells**
Allow supervisorctl override and maintain the sockfile during stop actions

### CODE REVIEW

**Comment by gsmethells** [comment]
This script works for me except for the changes I am making here. I believe others should benefit from these findings from production use, hence this pull request.

**Comment by gsmethells** [comment]
@mnaberez does this look good?

**Comment by gsmethells** [comment]
@mnaberez I could see sockfile being in /var/tmp/ as well, but went with /var/run/ here

**Comment by mnaberez** [comment]
> @mnaberez does this look good?

The Supervisor maintainers generally can't review or support these init scripts - they are all user contributed.  Have you tested these changes and do you feel it's ready to merge?  If so, I will merge it.

**Comment by gsmethells** [comment]
I’m using it in it production at several medical clinics and it works for me there. I haven’t rolled it out to all customers but enough that I’m willing to continue the roll out.

**Pull request merged**
